version: '3.7'

services:
  db:
    image: postgres:10.9-alpine
    volumes:
     - ./tmp/db:/var/lib/postgres/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DATABASE: gelatomio_development
      POSTGRES_USER: gelatomio
      POSTGRES_PASSWORD: 123456
